//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public Nullable<int> HireId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string BankVoucherNo { get; set; }
    
        public virtual Hire Hire { get; set; }
    }
}
