//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int ProgressId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string Comment { get; set; }
        public string PresentDays { get; set; }
    }
}
