//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Hires = new HashSet<Hire>();
            this.Hires1 = new HashSet<Hire>();
        }
    
        public int ScheduleId { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public Nullable<int> TutorId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Hire> Hires { get; set; }
        public virtual ICollection<Hire> Hires1 { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
