//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserInfo
    {
        public tblUserInfo()
        {
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int UserId { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
    
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
